spring:
  application:
    name: "user"

  config:
    import:
      - optional:file:env/user.env[.properties]

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
