spring:

  jwt:
    secret: ${JWT_SECRET_KEY}
    prefix: Bearer
    header: Authorization
    access:
      expiration: 3600000 # 1시간
    refresh:
      expiration: 2592000000 # 30일

  auth:
    google:
      redirect-uri: ${GOOGLE_REDIRECT_URI}
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
    naver:
      redirect-uri: ${NAVER_REDIRECT_URI}
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
    kakao:
      redirect-uri: ${KAKAO_REDIRECT_URI}
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}

server:
  redirect: "http://localhost:3000"
