spring:
  application:
    name: "user"

  config:
    import:
      - optional:file:env/user.env[.properties]

  profiles:
    active: oauth

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

logging:
  level:
    org:
      springframework:
        security: debug
