spring:
  jwt:
#    secret: ${JWT_SECRET_KEY}
    private-key-path: ${JWT_PRIVATE_KEY_PATH}
    public-key-path: ${JWT_PUBLIC_KEY_PATH}
    prefix: Bearer
    header: Authorization
    access:
      expiration: 3600000 # 1시간
    refresh:
      expiration: 2592000000 # 30일

  auth:
    google:
      base-url: ${GOOGLE_BASE_URL}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
      client-id: ${GOOGLE_CLIENT_ID}
      secret-id: ${GOOGLE_CLIENT_SECRET}
    naver:
      base-url: ${NAVER_BASE_URL}
      redirect-uri: ${NAVER_REDIRECT_URI}
      client-id: ${NAVER_CLIENT_ID}
      secret-id: ${NAVER_CLIENT_SECRET}
    kakao:
      base-url: ${KAKAO_BASE_URL}
      redirect-uri: ${KAKAO_REDIRECT_URI}
      client-id: ${KAKAO_CLIENT_ID}
      secret-id: ${KAKAO_CLIENT_SECRET}

server:
  redirect: "http://localhost:3000"
